sonarqube:
  replicaCount: 1
  resources:
    limits:
      cpu: "1"
      memory: "2Gi"
    requests:
      cpu: "500m"
      memory: "1Gi"

  persistence:
    enabled: true
    storageClass: "local-path"
    accessMode: ReadWriteOnce
    size: 5Gi

  postgresql:
    enabled: true
    postgresqlPassword: sonar
    persistence:
      enabled: true
      storageClass: "local-path"
      size: 5Gi

  initSysctl:
    enabled: true
      vmMaxMapCount: 262144

  ingress:
    enabled: false

  elasticsearch:
    javaOpts: "-Xms512m -Xmx512m"

  sonarProperties:
    sonar.web.javaAdditionalOpts: "-Xmx512m"