Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "sonarqube-vm"
  config.vm.network "private_network", ip: "192.168.56.20"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "sonarqube-dev-vm"
    vb.memory = "4096"
    vb.cpus = 2
  end

  config.vm.provision "shell", path: "provision.sh"
end
